"""Persistent cache for the educational indicator notes (the "що це / до чого призводить" blurb).

A note is a pure function of the indicator (persona version + specimen + normalized name) — it does
NOT depend on any measured value — so it is generated by claude ONCE and stored in the DB, then
reused forever: across restarts, across reports, in the single-chart view AND the PDF. That way a
chart/table can always carry a description without the user ever waiting for the same note twice.
The render itself is fast (~1s); only these notes were slow, so persisting them is the whole win.

DB-aware (it bridges a session and ``labs.humanize.describe_indicator``); the LLM call still goes
through ``describe_indicator`` (which routes to ``run_claude``), so no new path to the model.
"""

from __future__ import annotations

import contextlib
from typing import Any, cast

from sqlalchemy import CursorResult, delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from dbaylo.db.models import IndicatorNote
from dbaylo.labs.humanize import describe_indicator, note_cache_key


async def fetch_cached(session: AsyncSession, keys: list[str]) -> dict[str, str]:
    """Already-persisted notes for these cache keys (no generation). Bulk read."""
    if not keys:
        return {}
    rows = await session.scalars(
        select(IndicatorNote).where(IndicatorNote.cache_key.in_(list(set(keys))))
    )
    return {row.cache_key: row.text for row in rows}


async def purge_stale_versions(session: AsyncSession, *, current_version: str) -> int:
    """Delete notes from a PREVIOUS persona version (their cache key does not start with the current
    version tag), so a bumped ``INDICATOR_NOTE_VERSION`` leaves no orphan rows that are never read
    again. Returns how many were removed. Keys are ``"{version}\\x1f{specimen}\\x1f{analyte}"``."""
    prefix = f"{current_version}\x1f"
    result = await session.execute(
        delete(IndicatorNote).where(~IndicatorNote.cache_key.like(f"{prefix}%"))
    )
    return cast("CursorResult[Any]", result).rowcount or 0


async def store_many(session: AsyncSession, mapping: dict[str, str]) -> None:
    """Persist freshly generated notes. Skips empties and tolerates a duplicate-key race."""
    for key, text in mapping.items():
        if not text:
            continue
        if await session.get(IndicatorNote, key) is not None:
            continue
        session.add(IndicatorNote(cache_key=key, text=text))
    with contextlib.suppress(Exception):
        await session.flush()


async def get_note(session: AsyncSession, *, analyte: str, specimen: str | None) -> str:
    """One indicator's note: persisted cache → generate (claude) → persist. "" on failure."""
    key = note_cache_key(specimen, analyte)
    row = await session.get(IndicatorNote, key)
    if row is not None:
        return row.text
    note = await describe_indicator(analyte, specimen=specimen)
    if note:
        await store_many(session, {key: note})
    return note
