"""lab report status

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-19 01:07:19.425776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_reports", schema=None) as batch_op:
        # server_default so the NOT NULL column backfills cleanly on existing rows.
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("PENDING", "CONFIRMED", "DISCARDED", name="reportstatus"),
                nullable=False,
                server_default="PENDING",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_reports", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
