"""stage 5: lab conclusion + expert summary + per-result flagged

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-19 22:23:30.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, Sequence[str], None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("conclusion", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))

    with op.batch_alter_table("lab_results", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("flagged", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_results", schema=None) as batch_op:
        batch_op.drop_column("flagged")

    with op.batch_alter_table("lab_reports", schema=None) as batch_op:
        batch_op.drop_column("summary")
        batch_op.drop_column("conclusion")

    # ### end Alembic commands ###
