"""stage 6: narrative report kind/type/body

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-19 22:54:37.045724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.Enum('TABULAR', 'NARRATIVE', name='reportkind'), server_default='TABULAR', nullable=False))
        batch_op.add_column(sa.Column('report_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('narrative', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_reports', schema=None) as batch_op:
        batch_op.drop_column('narrative')
        batch_op.drop_column('report_type')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
