"""lab report birth_date for age-stratified refs

Revision ID: daa62c524484
Revises: 0012
Create Date: 2026-06-23 20:56:00.033726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: Union[str, Sequence[str], None] = "0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("birth_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_reports", schema=None) as batch_op:
        batch_op.drop_column("birth_date")

    # ### end Alembic commands ###
